[build-system]
requires = ["poetry", "Cython>=0.29.21", "setuptools", "wheel", "numpy"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "malva"
version = "0.2.0"
description = "malva: fast indexing and querying of genomic sequences from spatial transcriptomics data"
license = "GPL-2.0"
authors = [
    "Daniel León-Periñán <daniel.leonperinan@mdc-berlin.de>",
    "Nikolaos Karaiskos <nikolaos.karaiskos@mdc-berlin.de>",
]
maintainers = [
    "Daniel León-Periñán <daniel.leonperinan@mdc-berlin.de>",
    "Nikolaos Karaiskos <nikolaos.karaiskos@mdc-berlin.de>",
]
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Visualization",
]
include = ["malva/data/*.yaml", "malva/serve/static/index.html"]

[tool.poetry.build]
script = "build.py"
generate-setup-file = true

[tool.poetry.dependencies]
python = ">3.8,<3.12"
numpy = ">=1.17.0"
pandas = ">=1.0"
dnaio = ">1.0.0"
h5py = ">=3"
sortedcontainers = ">1.0.0"
rich = ">13.0"
pysam = ">0.20.0"
setproctitle = ">1.0"
tifffile = ">2022.4.8"
pyyaml = ">5.4"
netCDF4 = ">1.6.0"
xarray = ">2022.11.0"
datashader = ">0.15.0"
flask = ">2.3.0"
biopython = ">=1.83"
scikit-image = ">=0.24.0"
flask_session = ">=0.8.0"
ollama = ">=0.3.1"

[tool.poetry.dev-dependencies]
Cython = "^0.29.21"
pytest = ">=7.0.0"
pytest-cov = ">=4.0.0"
coverage = ">=7.0.0"

[tool.poetry.urls]
"Documentation" = "https://rajewsky-lab.github.io/malva"
"Source" = "https://github.com/rajewsky-lab/malva"
"Home-page" = "https://rajewsky-lab.github.io/malva"

[tool.poetry.scripts]
malva = 'malva.__main__:run_malva'

[tool.coverage.run]
plugins = ["Cython.Coverage"]
source = ["malva"]
parallel = true
branch = true
relative_files = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "pass",
    "raise Import.*"
]

[tool.coverage.html]
directory = "htmlcov"