# TODO: implement web server. To generate images from sequence, will use the logic from the `show` submodule
# TODO: this is an interactive flask application displaying an image
# that can be dynamically updated depending on the query sequence
# TODO: the image viewport has a default image, which is replaced as soon as the user enters a sequence
# and is generated by the underlying logic.
# TODO: simple: whole page contains image, then upper left there's a collapsible panel (floating)
# that will contain a single textbox for putting the query sequence (it is a nice mono-font
# up to 128 characters), then the textbox background will serve as a progressbar. The color of the
# panel is some beige, then the progress will be a very light, pastel blue. The interactive
# visualization is displayed as a plotly interactive image (see how to do this with flask),
# and the panel needs to be implemented in JS and CSS. Below the input box there is a selection
# dropdown with various color scales for the plotly visualization (viridis, inferno, grays)
# and below there is a button with a 'glass' button (as in 'find').
# The whole panel collapses when the mouse is not over it, and whenever entering or going out, there
# is a smooth, neat animation that toggles between the collapsed and non-collapsed state. There is another button
# next to the 'find' button that can be used to download the image and sequence (as a zip file of the TIFF file and
# the text as txt).

# TODO: this will use microfilm to display the images

def _run_serve(args):
    pass

if __name__ == "__main__":
    from katoste.cli import get_serve_parser
    args = get_serve_parser().parse_args()
    _run_serve()